// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjuhuvmaalbayrrjzznk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdWh1dm1hYWxiYXlycmp6em5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjY2MzYsImV4cCI6MjA2NjM0MjYzNn0.28GFATXEapY7yO6xPSqudEIIrR2B2Un6xJXk9ILb1P0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);